export { default as About } from './About';
export { default as Cart } from './Cart';
export { default as Checkout } from './Checkout';
export { default as Error } from './Error';
export { default as HomeLayout } from './HomeLayout';
export { default as Landing } from './Landing';
export { default as Login } from './Login';
export { default as Orders } from './Orders';
export { default as Products } from './Products';
export { default as Register } from './Register';
export { default as SingleProduct } from './SingleProduct';
export { default as SingleOrder } from './SingleOrder'
export { default as DashboardLayout } from './DashboardLayout';
export { default as AdminLogin } from './AdminLogin';
export { default as AdminRegister } from './AdminRegister';
export { default as Admins } from './Admins';
export { default as AdminCreate } from './AdminCreate';
export { default as AdminEdit } from './AdminEdit';
export { default as AdminUser } from './AdminUser';
export { default as AdminUserCreate } from './AdminUserCreate';
export { default as AdminUserEdit } from './AdminUserEdit';
export { default as AdminProducts } from './AdminProducts';
export { default as AdminProductsCreate } from './AdminProductsCreate';
export { default as AdminProductsEdit } from './AdminProductsEdit';
export { default as AdminOrder } from './AdminOrders'
export { default as AdminOrderEdit } from './AdminOrdersEdit'
export { default as AdminCategory } from './AdminCategory'
export { default as AdminCategoryEdit } from './AdminCategoryEdit'
export { default as AdminCategoryCreate } from './AdminCategoryCreate';